# Generated by Django 2.1.4 on 2020-04-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalBest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_date', models.DateField(auto_now_add=True)),
                ('pr_lift', models.CharField(max_length=50)),
                ('pr_weight', models.IntegerField()),
                ('pr_reps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_date', models.DateField(auto_now_add=True)),
                ('weight_weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_date', models.DateField(auto_now_add=True)),
                ('workout_duration', models.IntegerField()),
                ('workout_type', models.CharField(choices=[('run', 'run'), ('bike', 'bike'), ('lift', 'lift'), ('beach body lift', 'beach body lift'), ('beach body cardio', 'beach body cardio'), ('beach body boxing', 'beach body boxing'), ('lift from home', 'lift from home'), ('crossfit / HIT', 'crossfit / HIT')], default='lift', max_length=100)),
            ],
        ),
    ]
