# Generated by Django 2.1.4 on 2020-02-09 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50, unique=True)),
                ('book_author', models.CharField(max_length=100)),
                ('book_topic', models.CharField(choices=[('leadership', 'leadership'), ('self improvement', 'self improvement'), ('technology', 'technology'), ('story', 'story'), ('fiction', 'fiction'), ('sales', 'sales'), ('management', 'management')], default='leadership', max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['book_name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.TextField()),
                ('slug', models.SlugField(max_length=25)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Book')),
            ],
            options={
                'ordering': ['book'],
            },
        ),
    ]
